[runner]
runs_per_config = 10
parallel_jobs = 10
output_dir = "results_4"

[experiment]
algorithms = ["projet", "aco", "pso", "coverage", "flood_fill"]
length = 1
ticks_per_second = 2

[experiment.robots]
min = 1
max = 10
step = 1

[experiment.arena_size]
type = "Fixed"
value = 10

[experiment.seed]
type = "Uniform"
min = 1
max = 100000

[arena]
arena_type = ["scatter"]

[arena.maze_width]
type = "Fixed"
value = 10

[arena.maze_height]
type = "Fixed"
value = 10

[arena.scatter_density]
type = "Power"
min = 0.0001
max = 0.9
power = 1.5

[arena.scatter_size]
type = "Uniform"
min = 0.1
max = 2.0
