[runner]
runs_per_config = 10
parallel_jobs = 12
output_dir = "results"

[experiment]
algorithms = ["projet", "coverage", "aco", "pso"]
length = 10
ticks_per_second = 10

[experiment.robots]
min = 5
max = 20
step = 5

[experiment.arena_size]
type = "Fixed"
value = 10

[experiment.seed]
type = "Uniform"
min = 1
max = 100000

[arena]
arena_type = ["scatter"]

[arena.maze_width]
type = "Fixed"
value = 10

[arena.maze_height]
type = "Fixed"
value = 10

[arena.scatter_obstacles]
type = "Uniform"
min = 10
max = 50
