[runner]
runs = 4
parallel_jobs = 4
output_dir = "results"

[experiment]
length = 1000
ticks_per_second = 10

[experiment.robots]
type = "Uniform"
min = 5
max = 15

[experiment.arena_size]
type = "Fixed"
value = 10

[experiment.seed]
type = "Uniform"
min = 1
max = 100000

[arena]
arena_type = ["scatter", "maze"]

[arena.maze_width]
type = "Fixed"
value = 10

[arena.maze_height]
type = "Fixed"
value = 10

[arena.scatter_obstacles]
type = "Normal"
mean = 30.0
std_dev = 5.0
